apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: yerachw/inet-migration:latest
        env:
        - name: VERSION
          value: "1.0.0"
        envFrom:
        - configMapRef:
            name: envars
        - secretRef:
            name: secrets
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 1