kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-storage
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-01e0890a1aa8193a2
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

# For this to work we need a volume created in AWS with at least 15 GB
# The AWS voluem must have a tag: KubernetesCluster = <clustername>